console.log("Hello Mom");
let message = "working on it";
let price = 20;
console.log(message);
console.log(price);
let x = 30;
console.log(x);
x = 30 + 10;
console.log(x);
const speed = 70;
console.log(speed);
//let X = 5;
//let X = 35;
let X = 2;
let Y = 7;
//let z = X + Y;
//let z = X % Y;
//let z = X ** Y;
//x++
x--;
//z = x;
z = x++;
console.log(z);
